scrape_configs:
  - job_name:       'nuinvest'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 1m

    static_configs:
      - targets: ['nuinvest:5000']
        labels:
          group: 'production'